### ISSUE TITLE
Kanban Setting

### ISSUE THREAD

**Issue by benwmx** [benwmx/Javascript-capstone#21]
### Link to the repository : 
https://github.com/benwmx/Javascript-capstone/projects/1

### the Team Members (2) : 
- @ahzia 
- @benwmx

**Comment by vichuge** [comment]
# Project invalidated 🚫 

Hi there, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![cat_massage](https://user-images.githubusercontent.com/20563252/121368971-16d2dc00-c901-11eb-9123-7f578bf64118.gif)

## Why does this happen ❓ ❓ ❓ 

You have submitted a project, that doesn't have the link to their GitHub project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by benwmx** [comment]
hi @vichuge thank you for your review. I updated the issue to include the link to the Github project.

**Comment by carlos-ssh** [comment]
Hi @benwmx , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
Thanks, @carlos-ssh for Reviewing
